---

esphome:
  name: rainfall_device
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "="

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: ""

captive_portal:

external_components:
    - source:
      type: local
      path: components

i2c:
  sda: GPIO21
  scl: GPIO22

sensor:
  - platform: dfrobot_sen0575_i2c
    sensors:
      - name: "Rainfall Sensor"
        id: cumulative_rainfall
      - name: "Rainfall within 1 hour"
        id: rainfall_within_hour
      - name: "Raw Data"
        id: raw_data
      - name: "Sensor Working Time"
        id: sensor_working_time
